relativeURLs = true
title = "Alexander Gilså Hansen"
theme = "academimal"
sectionPagesMenu = "main"
defaultContentLanguage = "en"
ignorefiles = [ "hugo_travis_ci", ".travis.yml" ]

[params]
    shortbio = "PhD student in Economics at Stanford (matriculated 2024)"
    logo = "mefancy.jpg" 
    
